### ISSUE TITLE
NA results if matching on categorical variable with no equivalent value in non-treated group

### ISSUE THREAD

**Issue by sebbych** [pedrohcgs/DRDID#1]
Hi,

I realize that if one of the weighting variables in the formula is a categorical variable (e.g. taking value  1 to 4), and it happens that in the non-treated group some units do not have matching values (e.g. some units in the treated group have value 1 while no unit in the non-treated group has value 1), the ATT and SE are NA, without any warning message.
It was good for me because it forces me to double-check the balance of covariates before performing IPW.
But it may be helpful to have a warning message mentioning: "No match for value 1 in continuous variable X1"

I assume the solution is either to drop the treated units with this specific value unless there is a way to keep these units while ignoring weighting on this specific variable.

Best,

Sebbych

**Comment by pedrohcgs** [comment]
Hi, 
Do you mind providing a reproducible sample code where I can see how the error appears?
Thanks

**Comment by sebbych** [comment]
```
library(DRDID)
#load panel dataset on forest cover, distance to road, elevation, slope and biome
foo_amazonia <- readRDS(url("https://github.com/sebbych/amazonia/raw/main/foo_amazonia.rds"))


#run DRDID with biome
drdid(yname = "fcover", tname = "year", idname = "id", dname = "treat",
      xformla= ~ ldroad+lelevatn+lslope+biome,
      data = foo_amazonia, panel = TRUE)
#get NA findings
#explication may be that biome (exact matching variable) contains very few units on one value.

#run DRDID without biome
drdid(yname = "fcover", tname = "year", idname = "id", dname = "treat",
      xformla= ~ ldroad+lelevatn+lslope,
      data = foo_amazonia, panel = TRUE)
#now it works!
#but is there a way for DRDID to send me a message mentionnign that when i added biome, there is not enough units for some values?
```

**Comment by pedrohcgs** [comment]
Thanks! I've now added a more informative warning. Hope this helps.
