### ISSUE TITLE
Is IPW denominator correct in ipw_did_panel.R?

### ISSUE THREAD

**Issue by jtorcasso** [pedrohcgs/DRDID#2]
Consider the following block:

```R
  #Compute IPW estimator
  # First, the weights
  w.treat <- i.weights * D
  w.cont <- i.weights * ps.fit * (1 - D)/(1 - ps.fit)

  att.treat <- w.treat * deltaY
  att.cont <- w.cont * deltaY

  eta.treat <- mean(att.treat) / mean(i.weights * D)
  eta.cont <- mean(att.cont) / mean(i.weights * D)
```

For `eta.cont` we divide by `mean(i.weights * D)`, but shouldn't we divide by `w.cont`? I ran some simulations and found that the two quantities are the same when `i.weights=1` (i.e., no weights), but would they differ if we used non-trivial `i.weights`?

**Comment by pedrohcgs** [comment]
This is interesting. What you are suggesting is to use the normalized IPW estimator, which is what we do in ``std_ipw_did_panel.R``.  With unnormalized weights, this should be OK, I think.
