### ISSUE TITLE
Non-panel estimation requires ID

### ISSUE THREAD

**Issue by NickCH-K** [pedrohcgs/DRDID#3]
Just a quick note that the `idname` argument is non-optional, even if `panel = FALSE`. I managed to get `panel = FALSE` to run anyway by just using the row ID as the identifier (i.e. `1:N`) but not sure if this affected the results - I did get different results in Stata vs. R but not certain if this is why.

**Comment by pedrohcgs** [comment]
this is for the `drdid`, `ipwdid`, and `ordid` functions, right? I've just updated the documentation in the `panel` argument, but I am not sure if this is the only place where it was appearing. 

On R vs. Stata, do you the latest versions of both? Let me check with @friosavila about that!

**Comment by NickCH-K** [comment]
This is just in the R version where ID is required even in a non-panel setting. And I only checked drdid. Not sure if it's for the others too!

**Comment by pedrohcgs** [comment]
Closing this. Now idname always required.
